export const serviceColumns = [
    {
        value: "serviceName",
        label: "Name",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "flagIcon",
        label: "Icon",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
        isImage: true,
    },
    {
        value: "sortOrder",
        label: "Order",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "Action",
        label: "Action",
        color: "#FF5630",
        isFixed: false,
        isSort: false,
        isDisplay: true,
    },
];

export const portfolioColumns = [
    {
        value: "name",
        label: "Name",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "categoryId",
        label: "Category Name",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "sortOrder",
        label: "Sort Order",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "flagIcon",
        label: "Icon",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
        isImage: true,
    },
    {
        value: "image",
        label: "Images",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
        isImage: false,
        isCorosule: true,
    },
    {
        value: "Action",
        label: "Action",
        color: "#FF5630",
        isFixed: false,
        isSort: false,
        isDisplay: true,
    },
];
export const FaqColumns = [

    {
        value: "categoryId",
        label: "Category Name",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "question",
        label: "Question",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "answer",
        label: "Answer",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "Action",
        label: "Action",
        color: "#FF5630",
        isFixed: false,
        isSort: false,
        isDisplay: true,
    },
];

export const categoryColumns = [
    {
        value: "categoryName",
        label: "Category",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "categoryTitle",
        label: "Title",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "serviceId",
        label: "Service Name",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "tumbnail",
        label: "Thumbnail",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
        isImage: true,
    },
    {
        value: "price",
        label: "Price",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "discount",
        label: "Discount",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },

    {
        value: "rating",
        label: "Rating",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "image",
        label: "Images",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
        isImage: false,
        isCorosule: true,
    },
    {
        value: "formatIncluded",
        label: "Format Included",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
        isBadge: true,
        watchlist_value: "calculation_tags"
    },
    {
        value: "llikeReference",
        label: "Like reference",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "sortOrder",
        label: "Order",
        color: "#00B8D9",
        isFixed: true,
        isSort: false,
        isDisplay: true,
    },
    {
        value: "Action",
        label: "Action",
        color: "#FF5630",
        isFixed: false,
        isSort: false,
        isDisplay: true,
    },
];